version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data:
